env:
  global:
  - SAUCE_USERNAME: polyfiller
  - secure: "DuOlI2XmwJqRSuu0inhAJQD+YWPjXWy1Z2GLuj6A7y1/4ZzLtQuqalEORfOA2RG5YVaHDzffuNTuRkwX3Gz5DpG4zoFqsN/YCmwtfIs4lteSMQzli+qZQucMjY5NYWtWPlTeH7Xts82mrkOfsU8+XDIBvRWkdIpclCAC4cKa8+A="

notifications:
  email: false

language: node_js

node_js:
  - "io.js"
  - "0.12"
  - '0.10'

before_install:
    - npm install -g grunt-cli

install:
    - npm install

before_script:
  - grunt test

after_success:
  - grunt coveralls:api karma:client
